#ifndef __LEDPANEL_H
#define __LEDPANEL_H

#define BIT0 1
#define BIT1 2
#define BIT2 4
#define BIT3 8
#define BIT4 16
#define BIT5 32
#define BIT6 64
#define BIT7 128

#define LEDPANELDATAPORT    GPIO_PORTB_BASE
#define LEDPANELCONTROLPORT GPIO_PORTE_BASE
#define LEDROWSELECTMASK    BIT0 | BIT1 | BIT2
#define LEDCLOCKMASK        BIT3
#define LEDSTROBEMASK       BIT4
#define LEDOEMASK           BIT5
#define FRAMERATECHECKMASK  BIT3
#define LEDDATAMASK         BIT0 | BIT1 | BIT2 | BIT4 | BIT5 | BIT6
#define LEDWRITEDATA        LEDPANELDATAPORT, LEDDATAMASK
#define LEDWRITECLOCK       LEDPANELCONTROLPORT, LEDCLOCKMASK
#define LEDWRITESTROBE      LEDPANELCONTROLPORT, LEDSTROBEMASK
#define LEDOUTPUTENABLE     LEDPANELCONTROLPORT, LEDOEMASK
#define LEDROWADDRESS       LEDPANELCONTROLPORT, LEDROWSELECTMASK
#define FRAMERATECHECK      LEDPANELDATAPORT, FRAMERATECHECKMASK

#define LEDROWCOUNT 8            //Row select count = 8 for 1/8 scan rate display
#define LEDPIXELSPERSEGMENT 64   //Scan row crosses 2 display lines
#define LEDREGIONCOUNT      2    //Top and bottom
#define LEDPLANECOUNT       3
#define LEDREDCHANNEL       0x1
#define LEDGREENCHANNEL     0x02
#define LEDBLUECHANNEL      0x04

#define LEDTIMERPERIOD      500

#endif
